---
- name: ansible version check
  hosts: localhost
  tags: always
  tasks:
    - name: check if user is using correct ansible version
      fail:
        msg: "Unsupported ansible version {{ ansible_version.string }}. Please use {{ expected_ansible_version }} . Run `pip uninstall ansible` until it has nothing more to uninstall, then `pip3 install -U ansible=={{ expected_ansible_version }}`"
      when: ansible_version.full | version_compare(expected_ansible_version, "<")

    - name: check if user is using correct python version
      fail:
        msg: "Your ansible runs on python {{ ansible_python_version }}. Please checkout the README.md and upgrade to >= {{ expected_python_version }}"
      when:
        - ansible_python_version | version_compare(expected_python_version, "<")

# - name: Run deferred setup to gather facts
#   hosts: all
#   tags: always
#   tasks:
#     - setup:
#       vars:
#         ansible_become: no
