---
- name: install network add-on
  command: kubectl apply -f /srv/services/kubernetes/conf/kube-flannel.yml

- name: join master replica node
  shell: |
   kubeadm reset -f
   KUBE_JOIN_CMD="`cat {{ kubernetes_host_dir }}/conf/kubeadm_join_token | grep -oPz 'kubeadm\sjoin(.|\n)*?\n$'` --apiserver-advertise-address={{ net_internal_ip }}"
   bash -c "${KUBE_JOIN_CMD}"
