---

- name: install docker
  yum: name=docker-ce state=installed

- name: create the systemd directory for docker
  file: path=/etc/systemd/system/docker.service.d state=directory

- name: create the ssl certification directory for docker
  file: path=/etc/docker/certs.d/docker.epmc-bdcc.projects.epam.com state=directory

- name: create the systemd docker options configuration file
  template: src=docker_opts.conf.j2 dest=/etc/systemd/system/docker.service.d/docker_opts.conf
  notify:
    - reload systemd
    - restart docker

- meta: flush_handlers

- name: Start Docker service
  tags: [start-all-services, docker]
  service: name=docker state=started enabled=true
